# Generated by Django 4.1.3 on 2022-11-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='unidades',
            new_name='unidades_solicitadas',
        ),
    ]
