# Generated by Django 4.1.2 on 2022-11-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_compras'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
